### ISSUE TITLE
Filter analysis that get output by date

### ISSUE THREAD

**Issue by JeffreyThiessen** [phac-nml/irida-staramr-results#19]
The program should accept an optional requirement for the cutoff date to download.
The program should only download and output analysis that ran on or after the date specified.

This feature is dependant on #18 as it is assumed that we may be downloading/outputting multiple files.

**Comment by mariellemanlulu** [comment]
Formatting of arguments: `-d`, `--date`, `YYYY-mm-dd`
For example:
```
irida-staramr-results -p 1 -d 2021-01-04 -u irida-user -o out.xlsx
```

This will export results from project 1, only exporting those results from analysis ran since **January 4, 2021**.

**Comment by mariellemanlulu** [comment]
# Requirement update

- Have two arguments (`--fromDate` and `--toDate`) instead of one `--date`

For example:
```
irida-staramr-results -p 1 --fromDate 2021-01-04  --toDate 2021-03-18 -u irida-user -pw pasword1 -o out.xlsx
```

This will export results from project 1, only exporting those results from analysis ran between 
**January 4, 2021** and **March 18, 2020**, inclusive.
