### ISSUE TITLE
User configuration

### ISSUE THREAD

**Issue by JeffreyThiessen** [phac-nml/irida-staramr-results#3]
* Accept a config file from the user in the command line
  * Parse a config file (.yml) 
    * Client ID
    * Client Secret
    * Base URL
* Prompt user for username (or accept from command line argument) and password
  * Use `getpass` to get user password when running

**Comment by mariellemanlulu** [comment]
### Changes in requirements for username and password.

#### Two ways of retrieving username and password:

1. Default (no arguments given for -u and/or -pw)
      - prompt user for both username and pass

or
	
2. With arguments ( `-u <username>` and/or `-pw <password>`)
      - accept the arguments and do not prompt the user
